import Head from "next/head";

type MetaProps = {
    title: string
}

const Meta = ({ title }: MetaProps) => {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default Meta;

